apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: PORT
          value: "8003"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: redis-url
        
        # Health Probes Configuration
        startupProbe:
          httpGet:
            path: /health/startup
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30  # Allow up to 5 minutes for startup
        
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 0  # No delay since startup probe handles initialization
          periodSeconds: 30       # Check every 30 seconds
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3     # Restart after 3 consecutive failures
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 0  # No delay since startup probe handles initialization
          periodSeconds: 10       # Check every 10 seconds
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3     # Remove from service after 3 consecutive failures
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 80
    targetPort: 8003
  type: ClusterIP

---
# Example HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
